<a href="https://colab.research.google.com/github/maielhadad99/Numpy_Pandas_Assignment/blob/main/Numpy_Pandas_Assigment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1) Generate an array of zeroes using inbuilt numpy function.
import numpy as geek
  
b = geek.zeros(2, dtype = int)
print("Matrix b : \n", b)
  
a = geek.zeros([2, 2], dtype = int)
print("\nMatrix a : \n", a)
  
c = geek.zeros([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#2) Run the given code and find the dot product of both arrays.
import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)

[[2 7 2 2]
 [8 8 9 8]
 [5 5 4 8]]
[[4 9 3]
 [6 7 5]
 [4 5 9]
 [9 6 4]]


In [ ]:
a.dot(b)

array([[ 76,  89,  67],
       [188, 221, 177],
       [138, 148, 108]])

In [ ]:
import pandas as pd


In [ ]:
#3)Read the csv file provided using pandas and display the first 5 entries

data = pd.read_csv("/content/data.csv")

In [ ]:
data.head()

OBJECTID                        UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0        21        Fort Stevenson State Park  ...   0.000284   0.135641
1        22           Beaver Lake State Park  ...   0.000129   0.080067
2        23  Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3        24           Fort Ransom State Park  ...   0.000444   0.128733
4        25        Grahams Island State Park  ...   0.000469   0.125546

[5 rows x 6 columns]

In [ ]:
#4)Describe the data with all features.

In [ ]:
data.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

In [ ]:
#5)Find the total count of missing values for each feature.

In [ ]:
data.isnull().count()

OBJECTID       25
UNIT_NAME      25
DESCRIPTION    25
ACRES          25
SHAPE.AREA     25
SHAPE.LEN      25
dtype: int64

In [ ]:
#6)Display all the unique values from the 'DESCRIPTION’ column.
data.DESCRIPTION.unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

In [ ]:
#7)Create a grouped table usin 'DESCRIPTION' as the grouping columns with the means of all the other columns.
data.groupby(["DESCRIPTION"]).mean()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

In [ ]:
#8)Generate a random sample of 10 rows from the data.
data.sample(n=10)

OBJECTID                                   UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
1         22                      Beaver Lake State Park  ...   0.000129   0.080067
18        39             Gunlogson State Nature Preserve  ...   0.000048   0.040465
2         23             Fort Abraham Lincoln State Park  ...   0.000399   0.119868
6         27                   Lake Metigoshe State Park  ...   0.000751   0.212196
13        36       Crow Flies High State Recreation Area  ...   0.000120   0.050518
7         28                  Lewis and Clark State Park  ...   0.000256   0.130420
22        44       Turtle Mountain State Recreation Area  ...   0.000345   0.086487
17        38         Fahlgren Park State Recreation Area  ...   0.000010   0.013294
19        40  Head of the Mountain State Nature Preserve  ...   0.000034   0.033885
9         30           Fort Mandan State Recreation Area  ...   0.000005   0.009396

[10 rows x 6 columns]

In [ ]:
#9)Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using Numpy.
data["New_feature"]= np.random.rand(25)
data

OBJECTID  ... New_feature
0         21  ...    0.085901
1         22  ...    0.105073
2         23  ...    0.375303
3         24  ...    0.759899
4         25  ...    0.290265
5         26  ...    0.927287
6         27  ...    0.198517
7         28  ...    0.369238
8         29  ...    0.207169
9         30  ...    0.804131
10        31  ...    0.877348
11        32  ...    0.626961
12        35  ...    0.701879
13        36  ...    0.191993
14        33  ...    0.528965
15        34  ...    0.142567
16        37  ...    0.819800
17        38  ...    0.452724
18        39  ...    0.450050
19        40  ...    0.041835
20        41  ...    0.715088
21        43  ...    0.742106
22        44  ...    0.217304
23        45  ...    0.700116
24        42  ...    0.031864

[25 rows x 7 columns]

In [ ]:
#10) Replace zero value of column 'OBJECTID' with mean value permanently.
m=data["OBJECTID"].mean()
data.OBJECTID.fillna(m)
data

OBJECTID  ... New_feature
0         21  ...    0.085901
1         22  ...    0.105073
2         23  ...    0.375303
3         24  ...    0.759899
4         25  ...    0.290265
5         26  ...    0.927287
6         27  ...    0.198517
7         28  ...    0.369238
8         29  ...    0.207169
9         30  ...    0.804131
10        31  ...    0.877348
11        32  ...    0.626961
12        35  ...    0.701879
13        36  ...    0.191993
14        33  ...    0.528965
15        34  ...    0.142567
16        37  ...    0.819800
17        38  ...    0.452724
18        39  ...    0.450050
19        40  ...    0.041835
20        41  ...    0.715088
21        43  ...    0.742106
22        44  ...    0.217304
23        45  ...    0.700116
24        42  ...    0.031864

[25 rows x 7 columns]